name: Push main to another repository

on:
  push:
    branches:
      - main

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          API_TOKEN_GITHUB: ${{secrets.DESTINATION_REPO_PAT}}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Clone the destination repository
          git clone https://${API_TOKEN_GITHUB}@github.com/chathura226/RecruitEase_Vercel.git RecruitEase_Vercel
          cd ..
          ls -alh 
          # Remove all files in the destination repository
          cd RecruitEase_Vercel
          git rm -rf .
          
          # Copy all files from source to destination
          cp -r ../. .
          
          # Commit and push changes
          git add .
          git commit -m "Update from source repository"
          git push origin main --force
          
