name: Push main to another repository

on:
  push:
    branches:
      - main

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          API_TOKEN_GITHUB: ${{secrets.DESTINATION_REPO_PAT}}
        run: |
          git config --global user.name "chathura226"
          git config --global user.email "chathuralakshan226@gmail.com"
          
          # Add new remote for the destination repository
          git remote add destination https://${API_TOKEN_GITHUB}@github.com/chathura226/RecruitEase_Vercel.git
          
          # Force push to the destination repository
          git push destination main:main --force