name: Push main to another repository

on:
  push:
    branches:
      - main

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to destination repository
        env:
          API_TOKEN_GITHUB: ${{secrets.DESTINATION_REPO_PAT}}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Clone the destination repository
          git clone https://${API_TOKEN_GITHUB}@github.com/chathura226/RecruitEase_Vercel.git RecruitEase_Vercel
          
          # Remove all files in the destination repository (except .git)
          find RecruitEase_Vercel -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
          
          # Copy all files from source to destination (excluding .git)
          rsync -av --exclude='.git' --exclude='.github' --exclude='RecruitEase_Vercel' ./ RecruitEase_Vercel/
          
          # Commit and push changes
          cd RecruitEase_Vercel
          git add .
          git commit -m "Update from source repository"
          git push origin main --force
